### ISSUE TITLE
Problem running test with Celery

### ISSUE THREAD

**Issue by jacksonofalltrades** [jezdez/hirefire#1]
When I try this:
http://localhost:8000/hirefire/&lt;HIREFIRE_TOKEN&gt;/info

I get the following exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Library/Python/2.7/site-packages/hirefire/contrib/django/middleware.py", line 64, in process_request
    return self.info(request)
  File "/Library/Python/2.7/site-packages/hirefire/contrib/django/middleware.py", line 52, in info
    'quantity': proc.quantity() or 'null',
  File "/Library/Python/2.7/site-packages/hirefire/procs/celery.py", line 68, in quantity
    return sum([self.channel._size(queue) for queue in self.queues])
AttributeError: 'Channel' object has no attribute '_size'

Any ideas? I haven't found any reference to this problem on the web. Thanks.

**Comment by mjtamlyn** [comment]
This would be fixed by #9

**Comment by mjtamlyn** [comment]
Resolved by 9dc36d4b969adf92803729848f8118a1b4a6103a
